pipeline {
    agent any

    environment {
        VENV_DIR = "venv"  // Virtual environment directory
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'git@github.com:avengers-p11/attendance-api.git'
            }
        }

        stage('Install System Dependencies') {
            steps {
                sh '''
                    # Update system and install Python 3.11 and necessary libraries
                    sudo apt-get update -y
                    sudo apt-get install -y python3.11 python3.11-venv python3.11-dev \
                        python3-pip libpq-dev gcc
                '''
            }
        }

        stage('Set Up Python Environment') {
            steps {
                sh '''
                    # Create virtual environment with Python 3.11
                    if [ ! -d "$VENV_DIR" ]; then
                        python3.11 -m venv $VENV_DIR  # Specify the virtual environment directory
                    fi

                    # Activate virtual environment and upgrade pip
                    . ${VENV_DIR}/bin/activate
                    pip install --upgrade pip
                '''
            }
        }

        stage('Install Poetry') {
            steps {
                sh '''
                    # Install Poetry in the virtual environment
                    . ${VENV_DIR}/bin/activate
                    pip install poetry
                '''
            }
        }

        stage('Install Python Dependencies') {
            steps {
                sh '''
                    # Activate the virtual environment
                    . ${VENV_DIR}/bin/activate
                    
                    # Install dependencies based on pyproject.toml
                    poetry install
                    
                    # Optionally install missing dependencies directly
                    pip install flask_caching voluptuous
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    # Activate the virtual environment and run tests with code coverage
                    . ${VENV_DIR}/bin/activate
                    coverage run -m pytest --cov=attendance_api --cov-report html:coverage-report --cov-report xml:coverage-report/coverage.xml
                '''
            }
        }
    }

    post {
        always {
            // Clean up the virtual environment after the build
            sh '''
                rm -rf $VENV_DIR
            '''
            archiveArtifacts artifacts: 'coverage-report/*.xml', allowEmptyArchive: true
            echo 'Pipeline completed.'
        }
        
        success {
            emailext(
                attachmentsPattern: 'coverage-report/*.xml',
                body: """${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}
More info at: ${env.BUILD_URL}""",
                to: 'anjalidhiman.as@gmail.com', 
                subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}"
            )
        }
        
        failure {
            emailext(
                to: 'anjalidhiman.as@gmail.com',
                subject: 'Jenkins Pipeline Failure: Salary-api',
                body: '''Hello,

The Jenkins pipeline has failed. Please check the logs.'''.stripIndent()
            )
        }
    }
}

