@Library('Jenkins-shared-libraries@main') _

pipeline {
    agent any

    tools {
        go 'GO'
    }

    environment {
        REPORT_FILE = "dependency_scan_report.txt"
        GOSEC_BIN = './bin'
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    // Call the shared library function for checkout
                    golang_clone_repo()
                }
            }
        }

        stage('Install GoSec') {
            steps {
                script {
                    // Call the shared library function to install GoSec
                    golangInstallGoSec()
                }
            }
        }

        stage('Dependency Scanning') {
            steps {
                script {
                    // Call the shared library function to scan dependencies
                    golangScanDependencies()
                }
            }
        }
    }

    post {
        always {
            script {
                emailext(
                    attachmentsPattern: "${REPORT_FILE}",
                    body: "Dependency scanning report is attached.",
                    subject: "Go Project Dependency Scanning Report",
                    to: "raman.tripathi.snaatak@mygurukulam.co"
                )
            }
        }
    }
}
