@Library('Jenkins-shared-libraries') _

pipeline {
    agent any

    stages {
        stage('Code Clone') {
            steps {
                script {
                    clone_repo()
                }
            }
        }

        stage('Code Compilation') {
            steps {
                script {
                    compile_code('Maven')
                }
            }
        }

        stage('Static Code Analysis') {
            steps {
                script {
                    bug_analysis('Sonar')
                }
            }
        }
    }

    post {
        success {
            script {
                // Ensure the correct report path and name
                send_email(
                    subject: "SonarQube Analysis Success: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                    body: """The SonarQube analysis has completed successfully.
                            \n\nPlease find the attached analysis report and log file.""",
                    reportPath: "target",
                    reportFile: "bugs-analysis-report.json",
                    logFile: "sonar_analysis_output.log",
                    toEmail: "it.mohitsaini@gmail.com"
                )
            }
        }

        failure {
            script {
                // Send an email when the analysis fails
                send_email(
                    subject: "SonarQube Analysis Failure: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                    body: """The SonarQube analysis has failed.
                            \n\nPlease find the attached analysis report and log file.""",
                    reportPath: "target",
                    reportFile: "bugs-analysis-report.json",
                    logFile: "sonar_analysis_output.log",
                    toEmail: "it.mohitsaini@gmail.com"
                )
            }
        }
    }
}
