@Library('Jenkins-shared-libraries@main') _

pipeline {
    agent any

    stages {
        stage('Code Clone') {
            steps {
                script {
                    clone_repo()
                }
            }
        }

        stage('Code Compilation') {
            steps {
                script {
                    compile_code('Maven')
                }
            }
        }

        stage('Bugs Analysis') {
            steps {
                script {
                    bug_analysis('Sonar')
                }
            }
        }
    }

      post {
        success {
            script {
               
                send_email(
                    "SonarQube Analysis Success: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                    "The SonarQube analysis has completed successfully.\n\nPlease find the attached analysis report.",
                    "target",  
                    "bugs-analysis-report.json",  
                    "it.mohitsaini@gmail.com"  
                )
            }
        }

        failure {
            script {
               
                send_email(
                    "SonarQube Analysis Failure: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                    "The SonarQube analysis has failed.\n\nPlease find the attached analysis report.",
                    "target",  
                    "bugs-analysis-report.json",  
                    "it.mohitsaini@gmail.com"  
                )
            }
        }
    }
}
