@Library('Jenkins-shared-libraries@main') _ 

pipeline {
    agent any

    environment {
        DEP_CHECK_PATH = '/opt/dependency-check/bin'  
        DEP_CHECK_REPORT_PATH = '/tmp/dependency-check-report.html'  
        COPY_REPORT_PATH = 'dependency-check-report.html'  
    }

    stages {
        stage('Clone Repository') {
            steps {
                script {
                    python_clone_repo()  
                }
            }
        }

        stage('Set Up Python Environment') {
            steps {
                script {
                    python_environment()  
                }
            }
        }

        stage('Poetry Lock') {
            steps {
                script {
                    poetry_lock()  
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    python_dependencies()  
                }
            }
        }

        stage('Install OWASP Dependency-Check') {
            steps {
                script {
                    installation_owsap()  
                }
            }
        }

        stage('Update OWASP Dependency-Check Scan') {
            steps {
                script {
                    update_owsap()  
                }
            }
        }

        stage('Run OWASP Dependency-Check Scanning') {
            steps {
                script {
                    scanning_owsap()  
                }
            }
        }

        stage('Archive Dependency Check Report') {
            steps {
               
                sh "cp ${DEP_CHECK_REPORT_PATH} ${COPY_REPORT_PATH}"

               
                archiveArtifacts allowEmptyArchive: true, artifacts: "${COPY_REPORT_PATH}", onlyIfSuccessful: true
            }
        }

        stage('Send Dependency Check Report Email') {
            steps {
                script {
                    
                    sh "ls -l ${COPY_REPORT_PATH}"  
                    
                   
                    emailext(
                        to: 'anjalidhiman.as@gmail.com',  
                        subject: "OWASP Dependency-Check Report - ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                        body: "Please find the attached Dependency-Check report for ${env.JOB_NAME} #${env.BUILD_NUMBER}.",
                        attachmentsPattern: "${COPY_REPORT_PATH}",  
                        mimeType: 'text/html'
                    )
                }
            }
        }
    }
}
