node {
    // Define tools and environment variables.
    def goHome = tool 'GO'
    def REPORT_FILE = "test_report.txt"

    try {
        stage('Checkout') {
            checkout([
                $class: 'GitSCM',
                branches: [[name: 'main']],
                userRemoteConfigs: [[url: 'git@github.com:avengers-p11/employee-api.git']]
            ])
        }

        stage('Test') {
            sh """
                export PATH=$PATH:${goHome}/bin
                go test -v > ${REPORT_FILE} 2>&1
            """
        }
    } catch (e) {
        currentBuild.result = 'FAILURE'
        throw e
    } finally {
        stage('Send Email') {
            emailext(
                attachmentsPattern: "${REPORT_FILE}",
                body: "Unit test report is attached.",
                subject: "Go Project Unit Test Report",
                to: "raman.tripathi.snaatak@mygurukulam.co"
            )
        }
    }
}
