@Library('Jenkins-shared-libraries') _

pipeline {
    agent any

    stages {
      
        stage('Code Clone') {
            steps {
                script {
                    clone_repo()  
                }
            }
        }

  
        stage('Unit Testing') {
            steps {
                script {
                    unit_testing('Maven')  
                }
            }
        }
    }

    post {
        success {
            script {
                send_email(
                    "Unit Testing Success: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                    "The unit tests have been executed successfully.\n\nPlease find the attached unit test report.",
                    "target",  
                    "unit-test-report.txt",  
                    "it.mohitsaini@gmail.com"  
                )
            }
        }

        failure {
            script {
                send_email(
                    "Unit Testing Failure: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                    "The unit tests have failed.\n\nPlease find the attached unit test report.",
                    "target",  
                    "unit-test-report.txt",  
                    "it.mohitsaini@gmail.com" 
                )
            }
        }
    }
}
