pipeline {
    agent any

    tools {
        go 'GO'  
    }
    
    environment {
        scannerHome = tool 'Sonar'  
       
    }

    stages {
        stage('Clone Repository') {
            steps {
                echo 'Cloning the repository...'
                git branch: 'main', url: 'git@github.com:avengers-p11/attendance-api.git'
            }
        }

        stage('Bug Analysis') {
            steps {
                echo 'Running SonarQube analysis for bugs...'
                script {
                    withSonarQubeEnv('Sonar') {  // Assuming 'Sonar' is configured in Jenkins Global Tool Configuration
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=employee \
                            -Dsonar.projectName=Employee-api \
                            -Dsonar.host.url=http://54.175.166.181:9000 \
                            -Dsonar.login=squ_4f371ade2db48dafec85157cda9d3d07e6a5c456 \
                            -Dsonar.java.binaries=target/classes \
                            -Dsonar.issue.types=BUG \
                            -Dsonar.report.export.path=bugs-report.txt
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            // Send email with bug analysis report as attachment
            emailext(
                attachmentsPattern: 'bugs-report.txt',
                body: "Bug analysis report is attached.",
                subject: "SonarQube Bug Analysis Report",
                to: "raman.tripathi.snaatak@mygurukulam.co"
            )
        }

        success {
            echo 'Bug analysis completed successfully.'
        }

        failure {
            echo 'Bug analysis failed.'
        }
    }
}
