---
- name: Stop jenkins
  ansible.builtin.service:
    name: jenkins
    state: stopped
- name: Remove jenkins keyring
  ansible.builtin.command:
    cmd: rm -rf /usr/share/keyrings/jenkins-keyring.asc
- name: Rmove apt repo
  ansible.builtin.command:
    cmd: rm -rf /etc/apt/sources.list.d/jenkins.list
- name: Uninstall jenkins package
  ansible.builtin.apt:
    name: jenkins
    state: absent
    purge: true
    autoremove: true
    autoclean: true

# sudo rm -rf /etc/apt/sources.list.d/jenkins.list
# sudo rm /usr/share/keyrings/jenkins-keyring.asc
# sudo apt-get purge jenkins
# sudo apt-get remove --purge jenkins
# sudo apt-get autoremove
