pipeline {
    agent any

    tools {
        maven 'Maven'  
    }

    environment {
        scannerHome = tool 'Sonar' 
    }

    stages {
        stage('Clone Repository') {
            steps {
                echo 'Cloning the repository...'
                git branch: 'main', url: 'git@github.com:avengers-p11/salary-api.git'
            }
        }

        stage('Code Compilation') {
            steps {
                sh '''
                    mvn compile > compilation-report.txt
                    cat compilation-report.txt
                '''
            }
        }

        stage('Static Code Analysis') {
            steps {
                script {
                    withSonarQubeEnv('Sonar') {
                        sh """
                          ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=salary \
                            -Dsonar.projectName=Salary-api \
                            -Dsonar.host.url=http://3.90.82.155:9000 \
                            -Dsonar.login=squ_4f371ade2db48dafec85157cda9d3d07e6a5c456 \
                            -Dsonar.java.binaries=target/classes \
                            -Dsonar.issue.types=Static \
                            -Dsonar.report.export.path=target/sonar-report.json
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
            archiveArtifacts artifacts: 'compilation-report.txt', allowEmptyArchive: true
            archiveArtifacts artifacts: 'target/sonar-report.json', allowEmptyArchive: true
        }
        success {
            echo 'Static code analysis completed successfully!'
            mail to: 'it.mohitsaini@gmail.com', 
                 subject: 'SonarQube Bug Analysis: Salary-api', 
                 body: '''The Jenkins pipeline has successfully completed.
Please find the attached reports for the bug analysis.''', 
                 attachmentsPattern: 'compilation-report.txt,target/sonar-report.json'
        }
        failure {
            echo 'Static code analysis failed.'
            mail to: 'it.mohitsaini@gmail.com', 
                 subject: 'Jenkins Pipeline Failure: Salary-api', 
                 body: '''The Jenkins pipeline has failed.
Please check the attached logs and reports for more details.''', 
                 attachmentsPattern: 'compilation-report.txt,target/sonar-report.json'
        }
    }
}
