node {
    def VENV_DIR = "venv"  // Virtual environment directory
    def scannerHome = tool 'Sonar'  // SonarQube scanner tool

    try {
        stage('Clone Repository') {
            git branch: 'main', url: 'git@github.com:avengers-p11/attendance-api.git'
        }

        stage('Install Dependencies') {
            sh '''
                sudo apt-get update -y
                sudo apt-get install -y python3 python3-venv python3-pip curl
            '''
        }

        stage('Setup Virtual Environment') {
            sh """
                # Create and activate virtual environment
                if [ ! -d "$VENV_DIR" ]; then
                    python3 -m venv $VENV_DIR
                fi
                . ${VENV_DIR}/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt || echo "No requirements.txt"
                pip install pytest
            """
        }

        stage('SonarQube Analysis') {
            withSonarQubeEnv('Sonar') {
                sh """
                    ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=attendance \
                        -Dsonar.projectName=Attendance-api \
                        -Dsonar.login=squ_4f371ade2db48dafec85157cda9d3d07e6a5c456 \
                        -Dsonar.python.version=3 \
                        -Dsonar.sources=.
                """
            }
        }
    } catch (Exception e) {
        currentBuild.result = 'FAILURE'
        
        // Failure email
        emailext(
            to: 'anjalidhiman.as@gmail.com',
            subject: 'Pipeline Failed: Attendance-api',
            body: 'The Jenkins pipeline has failed. Check the logs for details.'
        )
        throw e
    } finally {
        if (currentBuild.result == 'SUCCESS') {
            // Success email
            emailext(
                to: 'anjalidhiman.as@gmail.com',
                subject: 'Build SUCCESS: Attendance-api',
                body: "Build Successful: ${env.JOB_NAME} #${env.BUILD_NUMBER} - ${env.BUILD_URL}"
            )
        }
    }
}
