pipeline {
    agent any

    environment {
        REPORT_FILE = "compile_report.txt" // File to save compilation report
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'git@github.com:avengers-p11/employee-api.git'
            }
        }

        stage('Compile') {
            steps {
                // Run Go build and save the output to a report file
                sh "go build > ${REPORT_FILE} 2>&1"
            }
        }
    }

    post {
        always {
            // Send the compilation report via email
            emailext attachmentsPattern: "${REPORT_FILE}",
                     body: "Compilation report is attached.",
                     subject: "Go Project Compilation Report",
                     to: "it.mohitsaini@gmail.com"
        }
    }
}
