node {
  
    def goHome = tool 'GO'
    def REPORT_FILE = "compile_report.txt"

    try {
        stage('Checkout') {
            git branch: 'main', url: 'git@github.com:avengers-p11/employee-api.git'
        }

        stage('Compile') {
          
            sh """
                export PATH=${goHome}/bin:\$PATH
                go version
                go build > ${REPORT_FILE} 2>&1
            """
        }

        stage('Archive Report') {
            archiveArtifacts artifacts: REPORT_FILE, onlyIfSuccessful: true
        }
    } catch (e) {
        currentBuild.result = 'FAILURE'
        throw e
    } finally {
        stage('Send Email') {
            emailext attachmentsPattern: REPORT_FILE,
                     body: "Compilation report is attached.",
                     subject: "Go Project Compilation Report",
                     to: "raman.tripathi.snaatak@mygurukulam.co"
        }
    }
}
 
