name: Slack Notification on PR Opened or Merged

# Trigger the action on pull request events
on:
  pull_request:
    types:
      - opened
      - closed

# Jobs to run
jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      # Step to check out the code (required for most workflows)
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to send a notification to Slack
      - name: Send Slack Notification
        run: |
          # Determine the message based on the action (opened or closed)
          if [ "${{ github.event.action }}" == "opened" ]; then
            message="A new pull request has been opened by ${{ github.actor }}: ${{ github.event.pull_request.title }}"
          elif [ "${{ github.event.action }}" == "closed" ]; then
            message="The pull request has been closed by ${{ github.actor }}: ${{ github.event.pull_request.title }}"
          fi

          # Send the message to Slack using the webhook URL stored in GitHub secrets
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"$message\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

